### ISSUE TITLE
additional property name

### ISSUE THREAD

**Issue by skelso01** [Azure/terraform-azurerm-naming#21]
Hi,
first of all. I like this module. I just have a wish for future.
Is it possible to implement a property name, which will be cut at the end, to fit with all prefixes and or suffixesand type, that it fits to the max length?

Best regards
s.Kelso

**Comment by Nepomuceno** [comment]
This is the current behavior of the name property it automatically cuts if the name does not fit removing the end of the string

Have you found any problem with this?

**Comment by skelso01** [comment]
Yes and no. If I use the object with prefixes, and one prefix is very long, i do not have the type shortcut in the result name.
So I think ther could be an input which should always be shorten if needed to get all prefixes, suffixes, type shortcuts and unique chars, in the result name depending on the max length of the resource.

**Comment by Nepomuceno** [comment]
The provider currently always cut in the end so if your prefix alone are over 24 chars for example for a storage account name you will lose your name

let me see if I understood correctly:

Current behavior is 
[prefix] + [slug] + [random] + [suffix]  them cut to the max length

The behavior that you expected is

if [prefix] + [slug] + [random] > length 
cut prefix so you can fit [prefix] + [slug] + [random]

or do you think the behavior should be 

if [prefix] + [slug] + [random] > length 
cut random so you can fit [prefix] + [slug] + [random]
if cutting random it is not enough them cut prefix ?

**Comment by skelso01** [comment]
Yes, you understand what I mean.
I think the prefix and/or suffix should be shorten to have in all cases the slug and random in the result string. 
But which of prefix/suffix is more important and which to shorten in cases both are present I could not say.
Now where i'm thinking on it, this seems not so easy as I thought first.

**Comment by Nepomuceno** [comment]
Normally the recommendation it is just to use prefixes but suffixes makes easier when reading and organazing your resources. It is even in the description for the parameters.

It is a hard problem to try to know which part should we remove but there is always room to improve on trying to adapt that.

**Comment by Nepomuceno** [comment]
No comment in this issue since 2020 will close this.
trying to do this logic it is out of the scope of this module.
