### ISSUE TITLE
Azure Container Registry Naming

### ISSUE THREAD

**Issue by ArgonQQ** [Azure/terraform-azurerm-naming#22]
Hello,

while we're extending our infrastructure with the naming module we stumbled across the Azure Container Registry Naming. Me personally the **cr** would have been fine but for the Azure CLI its called **acr** and therefore it is not really convenient to use and also confusing. Is it possible to change this? 

```
container_registry = {
      name        = substr(join("", compact([local.prefix_safe, "cr", local.suffix_safe])), 0, 63)
      name_unique = substr(join("", compact([local.prefix_safe, "cr", local.suffix_unique_safe])), 0, 63)
      dashes      = false
      slug        = "cr" => "acr"
      min_length  = 1
      max_length  = 63
      scope       = "resourceGroup"
      regex       = "^[a-zA-Z0-9]+$"
    }
```

Example Articles:

- https://docs.microsoft.com/en-us/azure/container-registry/container-registry-best-practices#manage-registry-size
- https://docs.microsoft.com/en-us/azure/container-registry/

https://github.com/Azure/terraform-azurerm-naming/pull/23

**Comment by Nepomuceno** [comment]
As said in the PR it makes senseto do this change and since the module still in preview the change it is welcome

Thank yoiu for your contibution
