### ISSUE TITLE
cosmosdb_account

### ISSUE THREAD

**Issue by mcalik77** [Azure/terraform-azurerm-naming#24]
CosmosDB account has to be lowercase and if I use this module it was giving error because account name has to be lowercase. 
"name": "cosmosdb_account",
"regex": "^(?=.{1,63}$)[a-z0-9][a-zA-Z0-9-_.]+[a-zA-Z0-9]$"

**Comment by Nepomuceno** [comment]
Thank you will fix it

**Comment by Nepomuceno** [comment]
Closed by #39
