### ISSUE TITLE
Deleting a naming block from a composite module causes "Provider configuration not present" errors.

### ISSUE THREAD

**Issue by EklipZgit** [Azure/terraform-azurerm-naming#31]
Should be fixed in https://github.com/Azure/terraform-azurerm-naming/pull/30

You can repro the issue in current code by simply adding something like this to any parent module:
```
module "bug_naming" {
  source = "Azure/naming/azurerm"
  suffix = [lower(var.datacenter), "dvo", lower(var.environment), lower(var.component)]
}

# This one doesn't matter, just use the bug_naming for something.
module "create_fancy_resource_group" {
  source = "../../submodules/fancy-resource-group"

  resource_group_name = module.bug_naming.resource_group.name
}

# add some third resource so you have something left over after the first two are removed.
```
terragrunt/terraform apply, and then comment out those two resources and try to apply again. You will get

```
Error: Provider configuration not present

To work with module.bug_naming.random_string.main its original provider
configuration at
module.bug_naming.provider["registry.terraform.io/hashicorp/random"] is
required, but it has been removed. 
```

**Comment by EklipZgit** [comment]
I believe https://github.com/Azure/terraform-azurerm-naming/pull/30 fixes this, more details in that PR

**Comment by EklipZgit** [comment]
#35 should properly fix this, I didn't realize before that that file I modified was generated elsewhere and would be rolled back when regenerated without this additional change.

**Comment by Nepomuceno** [comment]
Number #35 FIxed this I think in case it doesn't we can reopen this issue.
