### ISSUE TITLE
Request: Include location in naming

### ISSUE THREAD

**Issue by ilspiert** [Azure/terraform-azurerm-naming#32]
Can you include the location as a 3 or 4 letter abbreviation? It has to be check how many letters are required to make all locations unique.

**Expected behavior**
Add an option to module configuration location, e.g.

```
module "naming" {
  source = "Azure/naming/azurerm"
#...
  prefix = "hello"
  location = "westus2"
#...
}
```

So the generated `module.naming.resource_group.name` is "hello-rg-wu2" (format "[prefix]-[resource-type]-[location]-[suffix]-[unique]"). For global resources to be consistent I suggest to use an abbreviation as well, or leave it empty. Maybe the community has an opinion on that.

**Comment by travisty-** [comment]
@fsettele I usually include the location in the suffix list when it makes sense to do so, and that's worked well in my experience.
It gives you the flexibility to use a short location name like wu2 or whatever naming convention your organization agrees upon. 

```
module "naming" {
  source = "Azure/naming/azurerm"
  suffix = [var.short_location, var.environment, var.app_name]
}

module.naming.resource_group.name => rg-wu2-prod-navigator
```

**Comment by Nepomuceno** [comment]
I think @travisty- Got it correct here no need to add this as a specific argument.
