### ISSUE TITLE
Use Terraform 0.13+ versions contraints

### ISSUE THREAD

**Issue by BzSpi** [Azure/terraform-azurerm-naming#43]
The versions constraints declaration has changed since Terraform 0.13.

The provider version should no longer be set in the provider declaration.

https://www.terraform.io/docs/modules/providers.html

**Comment by HorizonNet** [comment]
Isn't that already the case?

**Comment by BzSpi** [comment]
@HorizonNet You're right ! I only looked at the tag which is the only version pushed on registry. Hope it will be tagged soon.
