### ISSUE TITLE
Question: why no tags or releases since 0.1.0?

### ISSUE THREAD

**Issue by Jaykul** [Azure/terraform-azurerm-naming#51]
Can you update the version in the terraform repository, or at least tag master once in a while?

Once upon a time, there was a release (0.1.0) made to the terraform repository, and many terraform users were using it like this:
```tf
module "naming" {
  source = "Azure/naming/azurerm"
  ...
}
```

When terraform 0.14 came out, it deprecated version constraints, which causes warnings for anyone that's using this module from the terraform repository.

Of course, that version constraint is fixed here in the repo --and there are also a lot of new resource types-- but the only way we can currently take advantage of that is to use `source = "github.com/azure/terraform-azurerm-naming"` **without even a tagged version**...

**Comment by Jaykul** [comment]
I just re-read this, and I feel like it's whiny. I apologize. It was really meant to be a question: is there some other way for me to manage this? I am relatively new to terraform, but I've inherited a large code base, and the un-versioned github reference seems like a potential headache.

**Comment by Nepomuceno** [comment]
I will add a new tag to the repo with this new release
