### ISSUE TITLE
Naming module available via Terraform registry missing some outputs

### ISSUE THREAD

**Issue by bizintelligence** [Azure/terraform-azurerm-naming#61]
Hi, 

The naming module available at terraform registry link is missing these outputs. These are available in your code

![image](https://user-images.githubusercontent.com/8715959/121099632-8d0d0b00-c83b-11eb-9e24-033da93367ce.png)
![image](https://user-images.githubusercontent.com/8715959/121099657-9eeeae00-c83b-11eb-9846-b246689db1ee.png)

However, when I use 
module "naming" {
  source  = "Azure/naming/azurerm"
  version = "0.1.0"
}
then I don't see above outputs. I also checked the json file in the module folder created by above code and those outputs are not there.
https://registry.terraform.io/modules/Azure/naming/azurerm/latest

![image](https://user-images.githubusercontent.com/8715959/121099601-7d8dc200-c83b-11eb-8414-5b6a2ee20176.png)

**Comment by Nepomuceno** [comment]
Fixed on version 0.1.1
