### ISSUE TITLE
Is the module compatible with CDKTF?

### ISSUE THREAD

**Issue by akhileshnirapure** [Azure/terraform-azurerm-naming#64]
Hi,

I'm trying to leverage the module using CDKTF and c#, but it seems the names are not generated or I'm missing something?

 Error: Incorrect attribute value type
│
│   on cdk.tf.json line 62, in resource.azurerm_resource_group.CoreResourceGroup:
│   62:         "name": "${module.stacknaming.resource_group}",
│     ├────────────────
│     │ module.stacknaming.resource_group is object with 8 attributes
│
│ Inappropriate value for attribute "name": string required.

usage
var projectNaming = new Naming(this,"stack naming",new NamingOptions {
                    Suffix = new string[] {"myapp"}
            });
 
projectNaming.ResourceGroupOutput

I do not see 'name' property as described here 

https://github.com/Azure/terraform-azurerm-naming#usage

my CDKTF.json

"terraformModules": [{
        "name": "naming",
        "source": "Azure/naming/azurerm",
        "version": "0.1.0"
      }],

**Comment by waxb** [comment]
putting a `[\"name\"]` at the module output lines in the `cdk.tf.json` makes the plan run successfully. I don't know whether this issue is coming from the module or `cdktf` itself

**Comment by Nepomuceno** [comment]
Thx @waxb for pointing this out.
